
INSERT INTO Genres (ID, Name) VALUES ('Abenteuer', 'Abenteuer')
INSERT INTO Genres (ID, Name) VALUES ('Action', 'Action')
INSERT INTO Genres (ID, Name) VALUES ('Comedy', 'Comedy')
INSERT INTO Genres (ID, Name) VALUES ('Doku', 'Doku')
INSERT INTO Genres (ID, Name) VALUES ('Drama', 'Drama')
INSERT INTO Genres (ID, Name) VALUES ('Eastern', 'Eastern')
INSERT INTO Genres (ID, Name) VALUES ('Erotik', 'Erotik')
INSERT INTO Genres (ID, Name) VALUES ('Fantasy', 'Fantasy')
INSERT INTO Genres (ID, Name) VALUES ('Gangster', 'Gangster')
INSERT INTO Genres (ID, Name) VALUES ('History', 'History')
INSERT INTO Genres (ID, Name) VALUES ('Horror', 'Horror')
INSERT INTO Genres (ID, Name) VALUES ('Krieg', 'Krieg')
INSERT INTO Genres (ID, Name) VALUES ('Krimi', 'Krimi')
INSERT INTO Genres (ID, Name) VALUES ('Musik', 'Musik')
INSERT INTO Genres (ID, Name) VALUES ('Romantik', 'Romantik')
INSERT INTO Genres (ID, Name) VALUES ('SciFi', 'Science-Fiction')
INSERT INTO Genres (ID, Name) VALUES ('Thriller', 'Thriller')
INSERT INTO Genres (ID, Name) VALUES ('Western', 'Western')

INSERT INTO Languages (ID, Name, ShortName) VALUES ('de', 'deutsch', 'dt.')
INSERT INTO Languages (ID, Name, ShortName) VALUES ('en', 'englisch', 'en.')
